FROM python:3.8-buster

WORKDIR /app

RUN pip install fastapi uvicorn gunicorn

COPY . .

EXPOSE 5000 
CMD [ "gunicorn", "app_fastapi:app", "-b 0.0.0.0:5000", "--workers", "9", "--access-logfile", "/dev/stdout" ]
