FROM python:3.8-buster

WORKDIR /app

RUN pip install fastapi uvicorn gunicorn

COPY . .

EXPOSE 7000 
CMD [ "gunicorn", "app_fastapi:app", "-b 0.0.0.0:7000", "--worker-class", "uvicorn.workers.UvicornWorker", "--workers", "1", "--access-logfile", "/dev/stdout" ]
