# Test Support Container

FROM python:3.8-buster

WORKDIR /home

RUN pip install requests matplotlib python-dateutil psutil

RUN apt-get upgrade && apt-get update
RUN apt install vim -y
RUN apt install curl -y

ENTRYPOINT ["tail", "-f", "/dev/null"]
