FROM python:3.8-buster

WORKDIR /app

RUN pip install falcon gunicorn

COPY . .

EXPOSE 6000 
CMD [ "gunicorn", "app_falcon:app", "-b 0.0.0.0:6000", "--workers", "1", "--access-logfile", "/dev/stdout" ]
